### ISSUE TITLE
Command 'Babel AST Explorer: Open' resulted in an error

### ISSUE THREAD

**Issue by Rishabh-Streak** [JennieJi/vscode-babel-ast-explorer#11]
Error message  "(command 'babelAstExplorer.start' not found)"

**Comment by tujoworker** [comment]
I just installed it and get the same error. But found that a very old version (v0.0.2) is working. Hope we get a fix out for that, or at least a workaround, so we can use the latest versions.

**Comment by JennieJi** [comment]
👍 Thanks for reporting, will check this later

**Comment by JennieJi** [comment]
Reopen this, it's very wierd, I cannot reproduce this on my laptop

**Comment by JennieJi** [comment]
Hi @Rishabh-Streak @tujoworker pls try the lastest `0.1.7`, shall be able to open now.

**Comment by tujoworker** [comment]
Thank You so much! It works very well!
